[csvファイルの書き込み](## csvファイルの書き込み)

In [26]:
import csv

l = [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]
print(l)
# [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]

header = ['', 'a', 'b', 'c', 'd']
index = ['ONE', 'TWO', 'THREE']

[[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]


## csvファイルの書き込み

In [27]:
with open('writeTest.csv', 'w') as f:
    writer = csv.writer(f) # csvの書き込みを宣言
    writer.writerow(header) # headerの書き込み
    for i, row in zip(index, l):
        writer.writerow([i] + row)

## csvファイルの読み込み

In [13]:
with open('writeTest.csv') as f:
    rl = f.read()
print(rl)
testList = []
for row in rl.split('\n'):
    testList.append(row.split(','))
del testList[len(testList)-1]
print(testList)

,a,b,c,d
ONE,11,12,13,14
TWO,21,22,23,24
THREE,31,32,33,34

[['', 'a', 'b', 'c', 'd'], ['ONE', '11', '12', '13', '14'], ['TWO', '21', '22', '23', '24'], ['THREE', '31', '32', '33', '34']]


## k分割交差検証

k-fold によるデータの分割方法

In [25]:
import numpy as np
from sklearn.model_selection import KFold

kf = KFold(n_splits = 4)

for train, test in kf.split(testList):
    print('%s %s'% (train, test))
    trainSet = []
    for i in train:
        trainSet.append(testList[i])
    print('%s %s'% (np.array(trainSet), testList[test[0]]))

[1 2 3] [0]
[['ONE' '11' '12' '13' '14']
 ['TWO' '21' '22' '23' '24']
 ['THREE' '31' '32' '33' '34']] ['', 'a', 'b', 'c', 'd']
[0 2 3] [1]
[['' 'a' 'b' 'c' 'd']
 ['TWO' '21' '22' '23' '24']
 ['THREE' '31' '32' '33' '34']] ['ONE', '11', '12', '13', '14']
[0 1 3] [2]
[['' 'a' 'b' 'c' 'd']
 ['ONE' '11' '12' '13' '14']
 ['THREE' '31' '32' '33' '34']] ['TWO', '21', '22', '23', '24']
[0 1 2] [3]
[['' 'a' 'b' 'c' 'd']
 ['ONE' '11' '12' '13' '14']
 ['TWO' '21' '22' '23' '24']] ['THREE', '31', '32', '33', '34']


In [20]:
print(testList[0:2])

[['', 'a', 'b', 'c', 'd'], ['ONE', '11', '12', '13', '14']]
